name: Build with java and maven
on: [push]
jobs:
  build-with-maven:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
            java-version: '11'
            distribution: 'temurin'
            cache: maven
      - name: Build with Maven
        run: maven clean install
        
